
services:
  frontend:
    build:
      context: .
      dockerfile: Front/Dockerfile
    ports:
      - "8082:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Back/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
